development:
  host: localhost
  port: 27017
  database: posts_dev
  logfile: development.log
    
production:
  host: localhost
  port: 27017
  database: posts_prod
  logfile: production.log
    
environment: development
